### ISSUE TITLE
 download issue

### ISSUE THREAD

**Issue by NoIDont-Zhara** [chris124567/hulu#7] opened 2021-12-06 03:59 UTC
when you do multiple searches kinda close together you get this error

```
panic: Get "": unsupported protocol scheme ""

goroutine 1 [running]:
main.main()
        c:/Users/dir/dir/dir/main.go:115 +0x153b
```
I believe this might be Hulu limiting the number of people that can watch Hulu at a time as when I tried to watch in a browser it gave me that error.

**Comment by chris124567** [comment] 2021-12-06 19:29
You're right.   I encountered a couple times before but couldn't reproduce it reliability but yeah I think it's the Hulu device limit.   The problem is that we generate a new device GUID every time the program is opened (https://github.com/chris124567/hulu/blob/master/client/client.go#L35).  I can't just use a fixed GUID because then everyone who uses the program will have the same GUID and that will probably result in account bans.  The solution is probably going to be to write a random GUID to a file on the first run and then just reuse that for all subsequent runs.  I'll work on this when I get time.

**Comment by NoIDont-Zhara** [comment] 2021-12-08 10:24
alright, when you do that I had the idea that you could specify the GUID since it appears you can grab it from a cookie as well? at least I think so since it was another cookie I saw. BTW I'm making something in batch to use this program in a much easier way. ill be sure to add a thing to detect this so it doesn't just fail.

**Comment by naikrovek** [comment] 2021-12-14 16:12
> The solution is probably going to be to write a random GUID to a file on the first run and then just reuse that for all subsequent runs. I'll work on this when I get time.

That is exactly the solution I would employ.  Or, show us the GUID you are using and let us supply that GUID in later runs.

**Comment by chris124567** [comment] 2021-12-14 17:32
This'll be fixed along with the issue about EAB IDs this weekend.  Have some exams I need to focus on \:)

**Comment by chris124567** [comment] 2021-12-20 19:37
My Hulu Trial expired on the 7th.  I don't have any other cards so I can't just make a new account.  To be honest anyone with basic programming skills and knowledge of how to use the Chrome developer tools network tab could solve the current open issues.

**Comment by chris124567** [comment] 2021-12-21 17:42
Somehow generously offered me an account :) The GUID issue has been fixed in https://github.com/chris124567/hulu/commit/11966a356bf6a0d52a3f1a43c33985d89e9b0965.  You can now make many searches in a short amount of time with no problem.  You can specify a GUID with the HULU_GUID environment variable or i will default to a hash of your hostname converted to a UUID.  The other problem remaining is downloading.  The problem is not retrieving EAB IDs (the endpoint for getting these still works fine) but that Widevine revoked the key this program uses.  It also seems like the Satsuoni Chrome 2209 CDM is also no longer working due to an update from Google.  Unless I can get another private key this program will not work.  I will keep looking around.

**Comment by chris124567** [comment] 2021-12-21 21:57
Someone sent me a working private key and it works now (I was just able to download a movie and an episode of Family Guy)!  Ensure you have the latest version.

**Closed by chris124567** 2021-12-21 21:57 UTC
